/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_deonew_car_VideoActivity2 */

#ifndef _Included_com_example_deonew_car_VideoActivity2
#define _Included_com_example_deonew_car_VideoActivity2
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_deonew_car_VideoActivity2_COLOR_FormatI420
#define com_example_deonew_car_VideoActivity2_COLOR_FormatI420 1L
#undef com_example_deonew_car_VideoActivity2_COLOR_FormatNV21
#define com_example_deonew_car_VideoActivity2_COLOR_FormatNV21 2L
/*
 * Class:     com_example_deonew_car_VideoActivity2
 * Method:    sendH264Func
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_deonew_car_VideoActivity2_sendH264Func
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
