/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_deonew_car_VideoActivity2_MediaThread */

#ifndef _Included_com_example_deonew_car_VideoActivity2_MediaThread
#define _Included_com_example_deonew_car_VideoActivity2_MediaThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
